"""sensitive column flags

Revision ID: a6757affcb70
Revises: de9095b980f3
Create Date: 2026-09-06 15:53:25.230778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a6757affcb70'
down_revision: Union[str, None] = 'de9095b980f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default is required: the table may already hold rows, and a
    # NOT NULL column without one cannot be added to them.
    op.add_column(
        'columns',
        sa.Column('sensitive', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('datasets', sa.Column('sensitive_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets', 'sensitive_columns')
    op.drop_column('columns', 'sensitive')
    # ### end Alembic commands ###
